# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
