# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0002_auto_20170914_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='command',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ModifiedOn'),
        ),
        migrations.AlterField(
            model_name='commandoutput',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='commandoutput',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ModifiedOn'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ModifiedOn'),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreatedOn'),
        ),
        migrations.AlterField(
            model_name='step',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ModifiedOn'),
        ),
    ]
