# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0003_auto_20170914_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='project',
        ),
        migrations.AddField(
            model_name='command',
            name='output_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='step_order',
            field=models.IntegerField(default=1),
        ),
    ]
