# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:09
from __future__ import unicode_literals

from django.db import migrations

def add_statuses(apps, schema_editor):
    StepStatus = apps.get_model("django_assist","StepStatus")
    db_alias = schema_editor.connection.alias
    StepStatus.objects.using(db_alias).bulk_create([
        StepStatus(status_name="Not Started"),
        StepStatus(status_name="Running"),
        StepStatus(status_name="Completed"),
        StepStatus(status_name="Error"),
        StepStatus(status_name="Cancelled")
    ])

def remove_statuses(apps, schema_editor):
    StepStatus = apps.get_model("django_assist", "StepStatus")
    db_alias = schema_editor.connection.alias
    StepStatus.objects.using(db_alias).filter(status_name="Not Started").delete()
    StepStatus.objects.using(db_alias).filter(status_name="Running").delete()
    StepStatus.objects.using(db_alias).filter(status_name="Completed").delete()
    StepStatus.objects.using(db_alias).filter(status_name="Error").delete()
    StepStatus.objects.using(db_alias).filter(status_name="Cancelled").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0005_stepstatus'),
    ]


    operations = [
        migrations.RunPython(add_statuses, remove_statuses),
    ]
