# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0006_auto_20170918_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepstatus',
            name='status_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
