# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0009_auto_20170919_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_assist.StepStatus'),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(default='Not Started', max_length=50),
        ),
    ]
