# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0010_auto_20170919_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='status',
        ),
    ]
