# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:15
from __future__ import unicode_literals

from django.db import migrations, models

def add_steps(apps, schema_editor):
    StepStatus = apps.get_model("django_assist","StepStatus")
    not_started = StepStatus.objects.get(status_name="Not Started")
    not_started.step_set.create(step_name = "Django Version Check", step_order=1)
    not_started.step_set.create(step_name = "Create New Project", step_order=2)
    not_started.step_set.create(step_name = "Run Server Check", step_order=3)
    not_started.step_set.create(step_name = "Create New App", step_order=4)
    not_started.step_set.create(step_name = "Initial Migratation", step_order=5)
    not_started.step_set.create(step_name = "Create Admin user", step_order=6)
    not_started.step_set.create(step_name = "Create Models", step_order=7)
    not_started.step_set.create(step_name = "Make Migrations", step_order=8)
    not_started.step_set.create(step_name = "Migrate Models", step_order=9)
    

def remove_steps(apps, schema_editor):
    Step = apps.get_model("django_assist", "Step")
    db_alias = schema_editor.connection.alias
    
    Step.objects.using(db_alias).filter(step_name="Django Version Check").delete()
    Step.objects.using(db_alias).filter(step_name="Create New Project").delete()
    Step.objects.using(db_alias).filter(step_name="Run Server Check").delete()
    Step.objects.using(db_alias).filter(step_name="Create New App").delete()
    Step.objects.using(db_alias).filter(step_name="Initial Migratation").delete()
    Step.objects.using(db_alias).filter(step_name="Create Admin user").delete()
    Step.objects.using(db_alias).filter(step_name="Create Models").delete()
    Step.objects.using(db_alias).filter(step_name="Make Migrations").delete()
    Step.objects.using(db_alias).filter(step_name="Migrate Models").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0012_auto_20170920_0243'),
    ]

    
    operations = [
        migrations.RunPython(add_steps, remove_steps),
    ]
