# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:36
from __future__ import unicode_literals

from django.db import migrations

def add_commands(apps, schema_editor):
    Step = apps.get_model("django_assist","Step")
    step = Step.objects.get(step_name="Django Version Check")
    step.command_set.create(command_text='python -m django --version')
    
    step = Step.objects.get(step_name="Create New Project")
    step.command_set.create(command_text='django-admin startproject mysite')
    
    step = Step.objects.get(step_name="Run Server Check")
    step.command_set.create(command_text='python manage.py runserver')
    
    step = Step.objects.get(step_name="Create New App")
    step.command_set.create(command_text='python manage.py startapp polls')
    
    step = Step.objects.get(step_name="Initial Migratation")
    step.command_set.create(command_text='python manage.py migrate')
    
    step = Step.objects.get(step_name="Create Admin user")
    step.command_set.create(command_text='python manage.py createsuperuser')
    
    step = Step.objects.get(step_name="Create Models")
    step.command_set.create(command_text='echo create model classes then add your app to INSTALLED_APPS in settings file')
    
    step = Step.objects.get(step_name="Make Migrations")
    step.command_set.create(command_text='python manage.py makemigrations polls')
    
    step = Step.objects.get(step_name="Migrate Models")
    step.command_set.create(command_text='python manage.py migrate')

    

def remove_commands(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('django_assist', '0013_auto_20170921_1415'),
    ]

    operations = [
        migrations.RunPython(add_commands, remove_commands),
    ]
